// Command seedgen writes the SQL that provisions the simulated fleet in the CSMS database
// (charge points + driver idTags) and the matching teardown script.
//
// Tables and columns follow ev-backend DB/scripts/x_main/.../001_xmain_schema_v1.0.0.sql
// (public.saev_ocpp_charge_point, public.saev_ocpp_id_tag). A charger is only accepted by the OCPP
// server when its status is 'Active'.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/steam-a/bpp-load-simulator/internal/config"
)

const batch = 1000

func main() {
	var (
		cfgPath = flag.String("config", "configs/default.yaml", "run configuration (fleet size, id prefix, profiles, idtags)")
		outDir  = flag.String("out", "seed", "output directory")
		tenant  = flag.String("tenant", "loadtest", "value for saev_ocpp_charge_point.tenant_id")
		schema  = flag.String("schema", "public", "database schema holding the saev_ocpp_* tables")
		perStn  = flag.Int("chargers-per-station", 4, "chargers grouped under one charge_station_id")
	)
	flag.Parse()

	cfg, err := config.Load(*cfgPath)
	if err != nil {
		log.Fatal(err)
	}
	if cfg.UsesIDList() {
		log.Fatal("config uses ids_file (existing chargers); there is nothing to seed")
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		log.Fatal(err)
	}
	cp := fmt.Sprintf("%s.saev_ocpp_charge_point", *schema)
	tag := fmt.Sprintf("%s.saev_ocpp_id_tag", *schema)

	seed, err := os.Create(filepath.Join(*outDir, "seed.sql"))
	if err != nil {
		log.Fatal(err)
	}
	defer seed.Close()
	w := bufio.NewWriter(seed)
	defer w.Flush()

	fmt.Fprintf(w, "-- generated by seedgen from %s: %d chargers, %d valid idTags\nBEGIN;\n", *cfgPath, cfg.Chargers, cfg.ValidTagCount())
	for start := 0; start < cfg.Chargers; start += batch {
		end := min(start+batch, cfg.Chargers)
		fmt.Fprintf(w, "INSERT INTO %s (charge_point_id, charge_station_id, connectors, is_boot_notif_received, status, tenant_id, updated_at) VALUES\n", cp)
		for i := start; i < end; i++ {
			sep := ","
			if i == end-1 {
				sep = ";"
			}
			fmt.Fprintf(w, "('%s','%sSTN-%05d',%d,false,'Active','%s',now())%s\n",
				cfg.ChargePointID(i), cfg.IDPrefix, i / *perStn, cfg.ProfileFor(i).Connectors, *tenant, sep)
		}
	}
	valid := cfg.ValidTagCount()
	for start := 0; start < valid; start += batch {
		end := min(start+batch, valid)
		fmt.Fprintf(w, "INSERT INTO %s (id_tag, status, expiry_date) VALUES\n", tag)
		for i := start; i < end; i++ {
			sep := ","
			if i == end-1 {
				sep = ";"
			}
			fmt.Fprintf(w, "('%s','Accepted',now() + interval '10 years')%s\n", cfg.IDTag(i), sep)
		}
	}
	fmt.Fprintln(w, "COMMIT;\nANALYZE;")

	td, err := os.Create(filepath.Join(*outDir, "teardown.sql"))
	if err != nil {
		log.Fatal(err)
	}
	defer td.Close()
	like := cfg.IDPrefix + "%"
	fmt.Fprintf(td, `-- removes everything the load test created (matches charge point ids starting with %[2]q)
BEGIN;
DELETE FROM %[1]s.saev_ocpp_meter_value      WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_transaction      WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_message_log      WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_connector_status WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_vid_tag          WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_charge_point     WHERE charge_point_id LIKE '%[2]s';
DELETE FROM %[1]s.saev_ocpp_id_tag           WHERE id_tag LIKE '%[3]s';
COMMIT;
`, *schema, like, cfg.IDTags.Prefix+"%")
	log.Printf("wrote %s and %s", seed.Name(), td.Name())
}
